# Generated by Django 3.2.8 on 2021-10-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='notification',
            field=models.BooleanField(default=True),
        ),
    ]
