# Generated by Django 3.2.8 on 2021-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211018_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
