# Generated by Django 3.2.8 on 2021-10-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_pic_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pic_path',
            new_name='profile_pic',
        ),
    ]
