# Generated by Django 3.2.8 on 2021-10-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profile_pic_path_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
