# Generated by Django 3.2.8 on 2021-10-22 21:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_dentist_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='document_path',
            field=models.FileField(blank=True, upload_to=users.models.upload_to_document),
        ),
    ]
