# Generated by Django 3.2.8 on 2021-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_dentist_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Dentist', 'D'), ('Patient', 'P')], default='Patient', max_length=100),
        ),
    ]
