# Generated by Django 3.2.8 on 2021-10-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='exit', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
