# Generated by Django 3.2.8 on 2021-10-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
