# Generated by Django 3.2.8 on 2021-11-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
