# Generated by Django 3.2.8 on 2021-10-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20211026_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='slug',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='exit', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
