version: '3.9'
services:
  app:
    build: .
    restart: always
    env_file:
      - ".env"
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
  qgis:
    image: qgis/qgis:latest
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A smile worker -l info
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - redis
      - app

  celery-beat:
    build: .
    restart: always
    command: celery -A smile beat -l info
    volumes:
      - ./celerydata/beat/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=db 127.0.0.1 [::1]
    depends_on:
      - redis
      - celery
