# Generated by Django 3.2.8 on 2021-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('contact_id', models.CharField(max_length=255)),
                ('ifsc', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('WithDrawal', 'WithDrawal')], max_length=100)),
                ('payment_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_account', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('account_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DurationField(auto_created=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('service_type', models.CharField(choices=[('Treatment', 'Treatment'), ('Consultation', 'Consultation'), ('Appointment', 'Appointment')], default='Appointment', max_length=100)),
            ],
        ),
    ]
