# Generated by Django 3.2.8 on 2021-11-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Deposit', 'Deposit'), ('WithDrawal', 'WithDrawal')], max_length=100)),
                ('payment_id', models.CharField(max_length=255)),
                ('order_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='service_type',
            field=models.CharField(choices=[('Treatment', 'Treatment'), ('Consultation', 'Consultation'), ('Appointment', 'Appointment')], default='Appointment', max_length=100),
        ),
    ]
