# Generated by Django 3.2.8 on 2021-11-08 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20211103_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_account', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('is_active', models.BooleanField()),
                ('account_type', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='user_fund_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(blank=True)),
                ('contact_id', models.CharField(max_length=255)),
                ('ifsc', models.CharField(blank=True, max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='contact_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
