# Generated by Django 3.2.8 on 2021-11-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_contact_fundaccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='contact',
            name='account_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ifsc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
