# Generated by Django 3.2.8 on 2021-12-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20211114_1031'),
        ('payment', '0004_auto_20211114_2225'),
    ]

    operations = [
    ]
