# Generated by Django 3.2.8 on 2021-12-03 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0005_merge_0004_auto_20211114_1031_0004_auto_20211114_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('ifsc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ifsc',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='fundaccount',
            name='is_active',
        ),
        migrations.AddConstraint(
            model_name='fundaccount',
            constraint=models.UniqueConstraint(fields=('user_id', 'account_type'), name='FundAccount'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Card_Info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bank_Info', to=settings.AUTH_USER_MODEL),
        ),
    ]
