# Generated by Django 3.2.8 on 2021-12-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20211203_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='account_number',
            field=models.CharField(default='32', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='card_num',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
    ]
