# Generated by Django 3.2.8 on 2021-12-03 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0007_auto_20211203_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='bankinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Bank_Info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cardinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Card_Info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
