# Generated by Django 3.2.8 on 2021-12-03 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0008_auto_20211203_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user'),
            preserve_default=False,
        ),
    ]
