# Generated by Django 3.2.8 on 2021-11-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment', 'payment'), ('review', 'review'), ('update_profile', 'update_profile'), ('appointment', 'appointment')], max_length=100),
        ),
    ]
