# Generated by Django 3.2.8 on 2021-10-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211018_1736'),
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaiable_at', models.DateTimeField()),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaiable_at', models.DateTimeField()),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
                ('treatment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaialble_at', models.DateTimeField()),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_chat', to='appointment.appointment')),
                ('reciever_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reciever', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
