# Generated by Django 3.2.8 on 2021-10-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingappointment',
            old_name='avaiable_at',
            new_name='available_at',
        ),
    ]
