# Generated by Django 3.2.8 on 2021-11-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
        ('users', '0001_initial'),
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingappointment',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist'),
        ),
        migrations.AddField(
            model_name='pendingappointment',
            name='treatment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment'),
        ),
        migrations.AddField(
            model_name='pendingappointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availability',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist'),
        ),
        migrations.AddField(
            model_name='appointmentmessage',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_chat', to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentmessage',
            name='reciever_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentmessage',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentchat',
            name='appointment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentchat',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist'),
        ),
        migrations.AddField(
            model_name='appointmentchat',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
