# Generated by Django 3.2.8 on 2021-10-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availability',
            name='available_at',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pendingappointment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
