<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-10-27 05:42
=======
# Generated by Django 3.2.8 on 2021-10-27 08:10
>>>>>>> 263e619216c8b3c139c71790da3ddde705d507bb

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20211025_1947'),
        ('appointment', '0005_auto_20211023_2338'),
    ]

    operations = [
    ]
