# Generated by Django 3.2.8 on 2021-10-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_merge_0002_auto_20211025_1947_0005_auto_20211023_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
