# Generated by Django 3.2.8 on 2021-10-27 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointmentmessage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingappointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
