# Generated by Django 3.2.8 on 2021-10-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_pendingappointment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmessage',
            name='created_at',
        ),
    ]
