# Generated by Django 3.2.8 on 2021-11-18 20:03

from django.db import migrations, models
import treatment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('duration', models.TimeField()),
                ('photo', models.ImageField(default='medical\\medical_service.png', upload_to=treatment.models.upload_to)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
