# Generated by Django 3.2.8 on 2021-10-18 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20211018_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('duration', models.TimeField()),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
            ],
        ),
    ]
