# Generated by Django 3.2.8 on 2021-10-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment', '0003_alter_treatment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
