# Generated by Django 3.2.8 on 2021-11-18 20:03

import clinic.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('profile_pic', models.ImageField(default='media\\clinic_default.png', upload_to=clinic.models.upload_to)),
                ('bio', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
            ],
        ),
    ]
