# Generated by Django 3.2.8 on 2021-10-22 05:18

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='profilePic',
        ),
        migrations.AddField(
            model_name='clinic',
            name='profile_pic',
            field=models.ImageField(default='media\\clinic_default.png', upload_to=clinic.models.upload_to),
        ),
    ]
