# Generated by Django 3.2.8 on 2021-11-14 19:25

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_auto_20211022_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clinic',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='clinic',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
            preserve_default=False,
        ),
    ]
