# Generated by Django 3.2.8 on 2021-10-22 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_auto_20211021_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dentist', to=settings.AUTH_USER_MODEL),
        ),
    ]
