# Generated by Django 3.2.8 on 2021-11-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_slug'),
        ('review', '0003_alter_review_dentist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dentist', to='users.dentist'),
        ),
    ]
