# Generated by Django 3.2.8 on 2021-12-12 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField()),
                ('status', models.CharField(default='o', max_length=1)),
                ('starting_time', models.DateTimeField(blank=True)),
                ('ending_time', models.DateTimeField(blank=True)),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendingConsultation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duration', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dentist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_chat', to='consultation.consultation')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='consultationtask',
            constraint=models.UniqueConstraint(fields=('task_id', 'user_id', 'consultation_id'), name='ConsultationTask'),
        ),
        migrations.AddConstraint(
            model_name='consultationrequest',
            constraint=models.UniqueConstraint(fields=('dentist_id', 'user_id'), name='ConsultationRequest'),
        ),
    ]
