# Generated by Django 3.2.8 on 2021-11-26 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultation', '0001_initial'),
        ('users', '0001_initial'),
        ('treatment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationtask',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_chat', to='consultation.consultation'),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dentist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.dentist'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='treatment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treatment.treatment'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='consultationtask',
            constraint=models.UniqueConstraint(fields=('task_id', 'user_id', 'consultation_id'), name='ConsultationTask'),
        ),
        migrations.AddConstraint(
            model_name='consultationrequest',
            constraint=models.UniqueConstraint(fields=('dentist_id', 'user_id'), name='ConsultationRequest'),
        ),
    ]
