# Generated by Django 3.2.8 on 2021-10-28 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationmessage',
            name='reciever_id',
        ),
        migrations.AddField(
            model_name='consultationmessage',
            name='receiver_id',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_receiver', to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
