# Generated by Django 3.2.8 on 2021-12-12 12:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
         migrations.RemoveField(
             model_name='consultation',
            name='id',
            ),

        migrations.AddField(
            model_name='consultation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
