# Generated by Django 3.2.8 on 2021-11-15 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultation', '0002_auto_20211028_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('consultation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.consultation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='consultationtask',
            constraint=models.UniqueConstraint(fields=('task_id', 'user_id', 'consultation_id'), name='ConsultationTask'),
        ),
    ]
